insert into WORK_HOURS values("AU","Total","Total",33);
insert into WORK_HOURS values("AU","Total","Managers",41);
insert into WORK_HOURS values("AU","Total","Professionals",35);
insert into WORK_HOURS values("AU","Total","Technicians and associate professionals",34);
insert into WORK_HOURS values("AU","Total","Clerical support workers",30);
insert into WORK_HOURS values("AU","Total","Service and sales workers",25);
insert into WORK_HOURS values("AU","Total","Skilled agricultural, forestry and fishery workers",41);
insert into WORK_HOURS values("AU","Total","Craft and related trades workers",39);
insert into WORK_HOURS values("AU","Total","Plant and machine operators, and assemblers",38);
insert into WORK_HOURS values("AU","Total","Elementary occupations",28);
insert into WORK_HOURS values("AU","Male","Total",37);
insert into WORK_HOURS values("AU","Male","Managers",44);
insert into WORK_HOURS values("AU","Male","Professionals",39);
insert into WORK_HOURS values("AU","Male","Technicians and associate professionals",38);
insert into WORK_HOURS values("AU","Male","Clerical support workers",35);
insert into WORK_HOURS values("AU","Male","Service and sales workers",29);
insert into WORK_HOURS values("AU","Male","Skilled agricultural, forestry and fishery workers",42);
insert into WORK_HOURS values("AU","Male","Craft and related trades workers",40);
insert into WORK_HOURS values("AU","Male","Plant and machine operators, and assemblers",39);
insert into WORK_HOURS values("AU","Male","Elementary occupations",30);
insert into WORK_HOURS values("AU","Female","Total",29);
insert into WORK_HOURS values("AU","Female","Managers",37);
insert into WORK_HOURS values("AU","Female","Professionals",32);
insert into WORK_HOURS values("AU","Female","Technicians and associate professionals",30);
insert into WORK_HOURS values("AU","Female","Clerical support workers",29);
insert into WORK_HOURS values("AU","Female","Service and sales workers",23);
insert into WORK_HOURS values("AU","Female","Skilled agricultural, forestry and fishery workers",35);
insert into WORK_HOURS values("AU","Female","Craft and related trades workers",33);
insert into WORK_HOURS values("AU","Female","Plant and machine operators, and assemblers",31);
insert into WORK_HOURS values("AU","Female","Elementary occupations",23);
insert into WORK_HOURS values("UK","Total","Total",36);
insert into WORK_HOURS values("UK","Total","Managers",42);
insert into WORK_HOURS values("UK","Total","Professionals",39);
insert into WORK_HOURS values("UK","Total","Technicians and associate professionals",37);
insert into WORK_HOURS values("UK","Total","Clerical support workers",32);
insert into WORK_HOURS values("UK","Total","Service and sales workers",30);
insert into WORK_HOURS values("UK","Total","Skilled agricultural, forestry and fishery workers",39);
insert into WORK_HOURS values("UK","Total","Craft and related trades workers",41);
insert into WORK_HOURS values("UK","Total","Plant and machine operators, and assemblers",41);
insert into WORK_HOURS values("UK","Total","Elementary occupations",31);
insert into WORK_HOURS values("UK","Male","Total",40);
insert into WORK_HOURS values("UK","Male","Managers",45);
insert into WORK_HOURS values("UK","Male","Professionals",41);
insert into WORK_HOURS values("UK","Male","Technicians and associate professionals",40);
insert into WORK_HOURS values("UK","Male","Clerical support workers",36);
insert into WORK_HOURS values("UK","Male","Service and sales workers",34);
insert into WORK_HOURS values("UK","Male","Skilled agricultural, forestry and fishery workers",40);
insert into WORK_HOURS values("UK","Male","Craft and related trades workers",41);
insert into WORK_HOURS values("UK","Male","Plant and machine operators, and assemblers",42);
insert into WORK_HOURS values("UK","Male","Elementary occupations",35);
insert into WORK_HOURS values("UK","Female","Total",32);
insert into WORK_HOURS values("UK","Female","Managers",38);
insert into WORK_HOURS values("UK","Female","Professionals",36);
insert into WORK_HOURS values("UK","Female","Technicians and associate professionals",33);
insert into WORK_HOURS values("UK","Female","Clerical support workers",30);
insert into WORK_HOURS values("UK","Female","Service and sales workers",28);
insert into WORK_HOURS values("UK","Female","Skilled agricultural, forestry and fishery workers",34);
insert into WORK_HOURS values("UK","Female","Craft and related trades workers",35);
insert into WORK_HOURS values("UK","Female","Plant and machine operators, and assemblers",34);
insert into WORK_HOURS values("UK","Female","Elementary occupations",24);